[pytest]
pythonpath = .

markers =
    slow: 実行に時間がかかるテスト
    learning: 学習用テスト
    smoke: 基本機能を確認するスモークテスト
    small: 小規模テスト
    medium: 中規模テスト
    large: 大規模テスト

python_classes =
    Test*
    Given*
    When*
    *場合
    *が
    *は
    *の

python_functions =
    test_*
    then_*
    *こと
